import {
  WarehouseJob,
  FreightUnit,
  WarehouseLocation,
  YardTrailer,
  OperationalException,
  CustomerAccount,
  RateCardItem,
  CapitalAsset,
  WarehousePersonnel,
} from "./types";

export const SAMPLE_BEFORE_1 = "/images/truck-cargo-shift-wide.jpg";
export const SAMPLE_BEFORE_2 = "/images/busted-pallet-runners-close.jpg";
export const SAMPLE_AFTER = "/images/reworked-pallet-after.jpg";

export const INITIAL_CUSTOMERS: CustomerAccount[] = [
  {
    id: "CUST-001",
    name: "Swift Transportation Logistics",
    accountNumber: "DX-ACT-1008",
    billingTier: "enterprise",
    paymentTerms: "Net 30",
    activeJobsCount: 2,
    totalYtdSpend: 48200,
    contact: {
      name: "Sarah Jenkins",
      email: "sjenkins@swifttrans-demo.com",
      phone: "(602) 555-0182",
    },
    approvalPolicy: "auto_under_500",
  },
  {
    id: "CUST-002",
    name: "Knight Dedicated Fleet",
    accountNumber: "DX-ACT-1022",
    billingTier: "preferred",
    paymentTerms: "Net 30",
    activeJobsCount: 1,
    totalYtdSpend: 31500,
    contact: {
      name: "Dave Kowalski",
      email: "dkowalski@knight-demo.com",
      phone: "(602) 555-4491",
    },
    approvalPolicy: "auto_under_500",
  },
  {
    id: "CUST-003",
    name: "TQL Apex Freight Brokerage",
    accountNumber: "DX-ACT-1089",
    billingTier: "standard",
    paymentTerms: "Net 15",
    activeJobsCount: 1,
    totalYtdSpend: 19400,
    contact: {
      name: "Alex Rivera",
      email: "arivera@tql-demo.com",
      phone: "(513) 555-7721",
    },
    approvalPolicy: "always_require",
  },
  {
    id: "CUST-004",
    name: "Front Range Regional Foods",
    accountNumber: "DX-ACT-2041",
    billingTier: "enterprise",
    paymentTerms: "Net 30",
    activeJobsCount: 1,
    totalYtdSpend: 62800,
    contact: {
      name: "Elena Rostova",
      email: "erostova@frontrangefoods-demo.com",
      phone: "(303) 555-6612",
    },
    approvalPolicy: "auto_under_500",
  },
  {
    id: "CUST-005",
    name: "Rocky Mountain Beverage Co",
    accountNumber: "DX-ACT-2088",
    billingTier: "standard",
    paymentTerms: "Credit Card / Pre-pay",
    activeJobsCount: 1,
    totalYtdSpend: 12200,
    contact: {
      name: "Tom Bradley",
      email: "tbradley@rmbev-demo.com",
      phone: "(720) 555-8833",
    },
    approvalPolicy: "always_require",
  },
];

export const INITIAL_RATE_CARD: RateCardItem[] = [
  {
    id: "RC-01",
    category: "Rework Labor",
    code: "LABOR-STD",
    description: "Certified Forklift & Pallet Restack Labor",
    unit: "per_hour",
    standardRate: 125.0,
    rushMultiplier: 1.5,
    notes: "1.0 hr minimum; billed in 15-minute increments",
  },
  {
    id: "RC-02",
    category: "Materials",
    code: "PALLET-CHEP",
    description: "CHEP Heavy-Duty Blue 48x40 Pallet Exchange",
    unit: "per_pallet",
    standardRate: 22.0,
    rushMultiplier: 1.0,
  },
  {
    id: "RC-03",
    category: "Materials",
    code: "PALLET-STD",
    description: "Grade-A Standard 4-Way 48x40 Wooden Pallet",
    unit: "per_pallet",
    standardRate: 18.5,
    rushMultiplier: 1.0,
  },
  {
    id: "RC-04",
    category: "Materials",
    code: "WRAP-HEAVY",
    description: "80-Gauge High-Tension Stretch Film (Machine/Hand Wrap)",
    unit: "per_roll",
    standardRate: 25.0,
    rushMultiplier: 1.0,
  },
  {
    id: "RC-05",
    category: "Materials",
    code: "CORNER-BOARDS",
    description: "Heavy-Duty Edge Protector Corner Boards (Set of 4)",
    unit: "flat_fee",
    standardRate: 12.0,
    rushMultiplier: 1.0,
  },
  {
    id: "RC-06",
    category: "Cross-Dock / Transfer",
    code: "CROSS-PALLET",
    description: "Direct Cross-Dock Pallet Transfer (Live Load / Unload)",
    unit: "per_pallet",
    standardRate: 15.0,
    rushMultiplier: 1.3,
  },
  {
    id: "RC-07",
    category: "Cross-Dock / Transfer",
    code: "FLOOR-TRANSLOAD",
    description: "Floor-Loaded Cargo Unload & Palletization (up to 400 ctns)",
    unit: "flat_fee",
    standardRate: 450.0,
    rushMultiplier: 1.5,
  },
  {
    id: "RC-08",
    category: "Storage",
    code: "STORE-AMBIENT",
    description: "Short-Term Ambient Pallet Storage (First 48h included)",
    unit: "per_pallet_per_day",
    standardRate: 3.5,
    rushMultiplier: 1.0,
    notes: "Food-grade secure bays; 30-day max staging",
  },
  {
    id: "RC-09",
    category: "Accessorial",
    code: "SCALE-AXLE",
    description: "Scale Verification & Axle Weight Calibration Check",
    unit: "flat_fee",
    standardRate: 35.0,
    rushMultiplier: 1.0,
  },
  {
    id: "RC-10",
    category: "Accessorial",
    code: "DEBRIS-DISPOSAL",
    description: "Damaged Packaging / Broken Wood Debris Removal",
    unit: "flat_fee",
    standardRate: 45.0,
    rushMultiplier: 1.0,
  },
];
export const INITIAL_LOCATIONS: WarehouseLocation[] = [
  // 6 Dock Doors (Illustrative door layout)
  { id: "D-01", name: "Dock Door 1", zone: "INBOUND", capacityPallets: 26, currentPalletIds: [], temperature: "ambient", status: "available", notes: "Hydraulic leveler inspected" },
  { id: "D-02", name: "Dock Door 2 (Rework Bay)", zone: "REWORK", capacityPallets: 26, currentPalletIds: ["DX-260918-033-P01", "DX-260918-033-P02", "DX-260918-033-P03"], temperature: "ambient", status: "full", notes: "Active Swift shifted pallets rework" },
  { id: "D-03", name: "Dock Door 3", zone: "INBOUND", capacityPallets: 26, currentPalletIds: ["DX-260918-037-P01", "DX-260918-037-P02", "DX-260918-037-P03", "DX-260918-037-P04"], temperature: "ambient", status: "partial", notes: "Flagship Job DX-260918-037 (RMB-5012)" },
  { id: "D-04", name: "Dock Door 4", zone: "CROSS-DOCK", capacityPallets: 26, currentPalletIds: ["DX-260918-035-P01"], temperature: "ambient", status: "partial", notes: "Unloading TQL floor transload" },
  { id: "D-05", name: "Dock Door 5 (Outbound)", zone: "OUTBOUND", capacityPallets: 26, currentPalletIds: ["DX-260918-039-P01", "DX-260918-039-P02"], temperature: "ambient", status: "full", notes: "Loading J.B. Hunt outbound freight" },
  { id: "D-06", name: "Dock Door 6", zone: "INBOUND", capacityPallets: 26, currentPalletIds: [], temperature: "ambient", status: "available", notes: "Available for expedited cross-dock" },

  // Dedicated Rework & Hold Areas
  { id: "RW-01", name: "Rework Zone 1 (High-Speed Restack)", zone: "REWORK", capacityPallets: 12, currentPalletIds: ["DX-260918-037-P01", "DX-260918-037-P02", "DX-260918-037-P08"], temperature: "climate_controlled", status: "partial", notes: "Equipped with turntable wrapper, banding cart, and restack station" },
  { id: "RW-02", name: "Rework Zone 2 (Manual Restack)", zone: "REWORK", capacityPallets: 12, currentPalletIds: [], temperature: "climate_controlled", status: "available", notes: "Manual restacking station" },
  { id: "HLD-01", name: "Quality Hold & Inspection Bay", zone: "HOLD", capacityPallets: 8, currentPalletIds: [], temperature: "climate_controlled", status: "available", notes: "Quarantine hold for claims review" },

  // Floor Staging & Cross-Dock Zones
  { id: "ST-01", name: "Staging Bay North-1", zone: "STAGING", capacityPallets: 30, currentPalletIds: [], temperature: "ambient", status: "available" },
  { id: "ST-02", name: "Staging Bay North-2", zone: "STAGING", capacityPallets: 30, currentPalletIds: [], temperature: "ambient", status: "available" },
  { id: "ST-03", name: "Staging Bay South-1 (Outbound)", zone: "STAGING", capacityPallets: 30, currentPalletIds: ["DX-260918-037-P05", "DX-260918-037-P06", "DX-260918-037-P07"], temperature: "ambient", status: "partial", notes: "Staged completed pallets ready for reload" },
  { id: "ST-04", name: "Staging Bay South-2", zone: "STAGING", capacityPallets: 30, currentPalletIds: [], temperature: "ambient", status: "available" },

  // High-Bay Rack Storage (Illustrative 30ft storage model)
  { id: "A-01", name: "Rack A-01 (Levels 1-4)", zone: "STORAGE", capacityPallets: 48, currentPalletIds: [], temperature: "climate_controlled", status: "available" },
  { id: "A-02", name: "Rack A-02 (Levels 1-4)", zone: "STORAGE", capacityPallets: 48, currentPalletIds: ["DX-260918-041-P01", "DX-260918-041-P02", "DX-260918-041-P03"], temperature: "climate_controlled", status: "partial", notes: "Front Range Food products staged" },
  { id: "A-03", name: "Rack A-03 (Levels 1-4)", zone: "STORAGE", capacityPallets: 48, currentPalletIds: [], temperature: "climate_controlled", status: "available" },
  { id: "A-04", name: "Rack A-04 (Levels 1-4)", zone: "STORAGE", capacityPallets: 48, currentPalletIds: [], temperature: "climate_controlled", status: "available" },
  { id: "B-01", name: "Rack B-01 (Levels 1-4)", zone: "STORAGE", capacityPallets: 48, currentPalletIds: [], temperature: "ambient", status: "available" },
  { id: "B-02", name: "Rack B-02 (Levels 1-4)", zone: "STORAGE", capacityPallets: 48, currentPalletIds: [], temperature: "ambient", status: "available" },
  { id: "B-03", name: "Rack B-03 (Levels 1-4)", zone: "STORAGE", capacityPallets: 48, currentPalletIds: [], temperature: "ambient", status: "available" },
  { id: "B-04", name: "Rack B-04 (Levels 1-4)", zone: "STORAGE", capacityPallets: 48, currentPalletIds: [], temperature: "ambient", status: "available" },
];
export const INITIAL_TRAILERS: YardTrailer[] = [
  {
    trailerNumber: "RMB-5012",
    carrier: "Regional Hotshot Logistics",
    carrierScac: "RHLX",
    jobId: "DX-260918-037",
    driverName: "Dan Kowalski",
    driverPhone: "(720) 555-9000",
    arrival: "2026-09-18T08:00:00-06:00",
    appointment: "2026-09-18T08:15:00-06:00",
    yardLocation: "Door 3",
    assignedDoor: "Door 3",
    loadStatus: "at_door",
    sealNumber: "SL-501201",
    sealIntact: true,
    departureStatus: "on_site",
    detentionStart: "2026-09-18T10:00:00-06:00",
    billOfLading: "BOL-44910-RMB",
  },
  {
    trailerNumber: "SWFT-55219",
    carrier: "Swift Transportation",
    carrierScac: "SWFT",
    jobId: "DX-260918-033",
    driverName: "Marcus Vance",
    driverPhone: "(720) 555-0194",
    arrival: "2026-09-18T07:45:00-06:00",
    appointment: "2026-09-18T08:00:00-06:00",
    yardLocation: "Door 2",
    assignedDoor: "Door 2",
    loadStatus: "at_door",
    sealNumber: "SL-881290",
    sealIntact: true,
    departureStatus: "on_site",
    detentionStart: "2026-09-18T09:45:00-06:00",
    billOfLading: "BOL-90218-SWFT",
  },
  {
    trailerNumber: "KNIG-44102",
    carrier: "Knight Transportation",
    carrierScac: "KNIG",
    jobId: "DX-260918-031",
    driverName: "David Ross",
    driverPhone: "(303) 555-9812",
    arrival: "2026-09-18T08:15:00-06:00",
    appointment: "2026-09-18T08:30:00-06:00",
    yardLocation: "Spot Y-03",
    assignedDoor: null,
    loadStatus: "waiting",
    sealNumber: "SL-441021",
    sealIntact: true,
    departureStatus: "on_site",
    detentionStart: "2026-09-18T10:15:00-06:00",
    billOfLading: "BOL-77312-KNIG",
  },
  {
    trailerNumber: "TQLX-90184",
    carrier: "Apex Line / TQL",
    carrierScac: "TQLX",
    jobId: "DX-260918-035",
    driverName: "John Miller",
    driverPhone: "(720) 555-4311",
    arrival: "2026-09-18T06:30:00-06:00",
    appointment: "2026-09-18T07:00:00-06:00",
    yardLocation: "Door 4",
    assignedDoor: "Door 4",
    loadStatus: "at_door",
    sealNumber: "SL-991440",
    sealIntact: true,
    departureStatus: "on_site",
    detentionStart: "2026-09-18T08:30:00-06:00",
    billOfLading: "BOL-55102-TQL",
  },
  {
    trailerNumber: "JBHT-33910",
    carrier: "J.B. Hunt Transport",
    carrierScac: "JBHT",
    jobId: "DX-260918-039",
    driverName: "Robert Hayes",
    driverPhone: "(303) 555-2144",
    arrival: "2026-09-18T08:40:00-06:00",
    appointment: "2026-09-18T08:45:00-06:00",
    yardLocation: "Door 5",
    assignedDoor: "Door 5",
    loadStatus: "at_door",
    sealNumber: "SL-102938",
    sealIntact: true,
    departureStatus: "on_site",
    detentionStart: "2026-09-18T10:40:00-06:00",
    billOfLading: "BOL-66129-JBHT",
  },
  {
    trailerNumber: "WRNR-88214",
    carrier: "Werner Enterprises",
    carrierScac: "WRNR",
    jobId: "DX-260918-043",
    driverName: "Carlos Mendez",
    driverPhone: "(720) 555-7791",
    arrival: "2026-09-18T05:50:00-06:00",
    appointment: "2026-09-18T06:00:00-06:00",
    yardLocation: "Spot Y-08",
    assignedDoor: null,
    loadStatus: "staged_ready",
    sealNumber: "SL-338821",
    sealIntact: true,
    departureStatus: "on_site",
    detentionStart: "2026-09-18T07:50:00-06:00",
    billOfLading: "BOL-88214-WRNR",
  },
  {
    trailerNumber: "SNLU-11048",
    carrier: "Schneider National",
    carrierScac: "SNLU",
    jobId: "DX-260918-045",
    driverName: "Kevin O'Connor",
    driverPhone: "(303) 555-4411",
    arrival: "2026-09-18T04:20:00-06:00",
    appointment: "2026-09-18T04:30:00-06:00",
    yardLocation: "Spot Y-12",
    assignedDoor: null,
    loadStatus: "departed",
    sealNumber: "SL-110480",
    sealIntact: false,
    departureStatus: "departed",
    detentionStart: "2026-09-18T06:20:00-06:00",
    billOfLading: "BOL-11048-SNLU",
  },
];

export const INITIAL_EXCEPTIONS: OperationalException[] = [
  {
    id: "EX-1049",
    jobId: "DX-260918-037",
    palletId: "DX-260918-037-P08",
    type: "leaning_pallet",
    severity: "critical",
    status: "awaiting_customer",
    title: "Severe Pallet Lean (>15°) on Pallet P08",
    description: "During rework in Bay RW-01, pallet P08 was determined to have severe load shift (>15° tilt) with sheared bottom runners and creased lower cases from hard braking on the I-70 Floyd Hill descent. Requires full manual restack, replacement Grade-A pallet exchange, machine re-wrap, and corner board installation.",
    discoveredTime: "11:06 AM",
    discoveredBy: "Lead Dock Tech Marco S.",
    location: "RW-01",
    photos: [SAMPLE_BEFORE_1, SAMPLE_BEFORE_2],
    recommendedAction: "1. Carefully un-case 72 cartons of bottled soda\n2. Transfer and hand-stack onto replacement Grade-A hardwood GMA pallet\n3. Inspect bottles for seal integrity\n4. Apply 80-gauge machine stretch film with 4 heavy-duty corner boards\n5. Inspect plumbness (<2° variance) & clear for reload into RMB-5012",
    originalScopeCoverage: "Standard Freight Rescue covers offload and visual inspection. Complete pallet restack, board replacement, and rebuild exceeds original authorized scope.",
    changeOrderAmount: 285.0,
    approvalState: "pending",
    approvalRequestedTime: "11:15 AM",
    customerViewedTime: undefined,
    approvalDecisionTime: undefined,
    approvedBy: undefined,
    approverContact: "tbradley@rmbev-demo.com • (720) 555-8833",
    resolutionState: "pending",
    auditHistory: [
      { id: "AUD-01", timestamp: "11:06 AM", action: "Exception Discovered", actor: "Marco S. (Lead Tech)", details: "Severe pallet lean (>15°) identified on P08 during Bay RW-01 rework" },
      { id: "AUD-02", timestamp: "11:09 AM", action: "Evidence Attached", actor: "Marco S. (Lead Tech)", details: "2 timestamped photographic evidence files captured via dock tablet" },
      { id: "AUD-03", timestamp: "11:14 AM", action: "Corrective Action Estimated", actor: "Dispatch Office", details: "Change order quoted at $285.00 for pallet rebuild, wrap, and replacement GMA board" },
      { id: "AUD-04", timestamp: "11:15 AM", action: "Approval Requested", actor: "Dispatch Office", details: "Electronic authorization link issued to Tom Bradley (Rocky Mountain Beverage Co)" },
    ],
    customerApprovalRequired: true,
    approvalStatus: "pending",
    additionalCost: 285.0,
    reportedAt: "2026-09-18T11:06:00-06:00",
    reportedBy: "Lead Dock Tech Marco S.",
    resolutionNotes: "Requires restack onto Grade-A pallet + 80-gauge wrap + 4 corner boards ($285.00 change order).",
  },
  {
    id: "EX-1050",
    jobId: "DX-260918-035",
    palletId: "DX-260918-035-P01",
    type: "crushed_cartons",
    severity: "medium",
    status: "resolved",
    title: "Bottom Tier Carton Creasing (Tier 1 & 2)",
    description: "Cartons compressed due to excessive top weight during intermodal container rail transit. Dry grocery contents intact.",
    discoveredTime: "07:20 AM",
    discoveredBy: "Forklift Tech Luis R.",
    location: "D-04",
    photos: [SAMPLE_BEFORE_2],
    recommendedAction: "Invert tier stacking during transload to relieve bottom carton stress.",
    originalScopeCoverage: "Covered under standard cross-dock transfer.",
    changeOrderAmount: 0.0,
    approvalState: "waived",
    resolutionState: "resolved",
    auditHistory: [
      { id: "AUD-50-01", timestamp: "07:20 AM", action: "Defect Logged", actor: "Luis R.", details: "Bottom tier creasing documented" },
      { id: "AUD-50-02", timestamp: "07:35 AM", action: "Resolved", actor: "Luis R.", details: "Inverted tier stacking completed" },
    ],
    customerApprovalRequired: false,
    approvalStatus: "waived",
    reportedAt: "2026-09-18T07:20:00-06:00",
    reportedBy: "Forklift Tech Luis R.",
    resolutionNotes: "Inverted tier stacking during transload to relieve bottom carton stress.",
  },
  {
    id: "EX-1051",
    jobId: "DX-260918-031",
    type: "count_discrepancy",
    severity: "high",
    status: "awaiting_customer",
    title: "BOL Count Mismatch (24 on BOL vs 22 in Trailer)",
    description: "Driver paper BOL states 24 pallets; visual seal-break inspection confirms 22 pallets with front bulkhead void.",
    discoveredTime: "08:35 AM",
    discoveredBy: "Receiving Clerk Dan W.",
    location: "Spot Y-03",
    photos: [SAMPLE_BEFORE_1],
    recommendedAction: "Hold offload until shipper confirms revised BOL count.",
    originalScopeCoverage: "Inbound gate verification.",
    changeOrderAmount: 0.0,
    approvalState: "pending",
    resolutionState: "pending",
    auditHistory: [
      { id: "AUD-51-01", timestamp: "08:35 AM", action: "Discrepancy Logged", actor: "Dan W.", details: "22 pallets found vs 24 stated on BOL" },
    ],
    customerApprovalRequired: true,
    approvalStatus: "pending",
    reportedAt: "2026-09-18T08:35:00-06:00",
    reportedBy: "Receiving Clerk Dan W.",
    resolutionNotes: "Waiting for shipper confirmation / amended bill before unloading.",
  },
];

export const INITIAL_PALLETS: FreightUnit[] = [
  // --- Flagship Job DX-260918-037 Freight Units (6 Pallets) ---
  {
    id: "DX-260918-037-P01",
    jobId: "DX-260918-037",
    palletNumber: 1,
    currentLocation: "RW-01",
    weightLbs: 2150,
    dimensions: { lengthIn: 48, widthIn: 40, heightIn: 72 },
    condition: "leaning",
    status: "in_rework",
    skuDescription: "Craft Root Beer Bottles (24x12oz Glass)",
    cartonCount: 84,
    photos: [SAMPLE_BEFORE_1, SAMPLE_BEFORE_2],
    movementHistory: [
      { id: "MOV-37-01", palletId: "DX-260918-037-P01", timestamp: "2026-09-18T08:20:00-06:00", fromLocation: "Trailer RMB-5012", toLocation: "D-03", operator: "Marco S.", reason: "Unloaded at Door 3 with extreme care" },
      { id: "MOV-37-02", palletId: "DX-260918-037-P01", timestamp: "2026-09-18T08:25:00-06:00", fromLocation: "D-03", toLocation: "RW-01", operator: "Marco S.", reason: "Transferred to Rework Zone 1 turntable for rebuild" },
    ],
  },
  {
    id: "DX-260918-037-P02",
    jobId: "DX-260918-037",
    palletNumber: 2,
    currentLocation: "RW-01",
    weightLbs: 2100,
    dimensions: { lengthIn: 48, widthIn: 40, heightIn: 70 },
    condition: "crushed_cartons",
    status: "in_rework",
    skuDescription: "Craft Ginger Ale (24x12oz Glass)",
    cartonCount: 84,
    photos: [SAMPLE_BEFORE_2],
    movementHistory: [
      { id: "MOV-37-03", palletId: "DX-260918-037-P02", timestamp: "2026-09-18T08:22:00-06:00", fromLocation: "Trailer RMB-5012", toLocation: "D-03", operator: "Marco S.", reason: "Unloaded from Door 3" },
      { id: "MOV-37-04", palletId: "DX-260918-037-P02", timestamp: "2026-09-18T08:28:00-06:00", fromLocation: "D-03", toLocation: "RW-01", operator: "Marco S.", reason: "Staged in Rework Zone 1 for repalletizing" },
    ],
  },
  {
    id: "DX-260918-037-P03",
    jobId: "DX-260918-037",
    palletNumber: 3,
    currentLocation: "D-03",
    weightLbs: 2120,
    dimensions: { lengthIn: 48, widthIn: 40, heightIn: 68 },
    condition: "good",
    status: "received",
    skuDescription: "Mountain Blackberry Soda (24x12oz)",
    cartonCount: 84,
    photos: [SAMPLE_AFTER],
    movementHistory: [
      { id: "MOV-37-05", palletId: "DX-260918-037-P03", timestamp: "2026-09-18T08:25:00-06:00", fromLocation: "Trailer RMB-5012", toLocation: "D-03", operator: "Marco S.", reason: "Unloaded at Door 3 staging" },
    ],
  },
  {
    id: "DX-260918-037-P04",
    jobId: "DX-260918-037",
    palletNumber: 4,
    currentLocation: "D-03",
    weightLbs: 2120,
    dimensions: { lengthIn: 48, widthIn: 40, heightIn: 68 },
    condition: "good",
    status: "received",
    skuDescription: "Mountain Blackberry Soda (24x12oz)",
    cartonCount: 84,
    photos: [SAMPLE_AFTER],
    movementHistory: [
      { id: "MOV-37-06", palletId: "DX-260918-037-P04", timestamp: "2026-09-18T08:27:00-06:00", fromLocation: "Trailer RMB-5012", toLocation: "D-03", operator: "Marco S.", reason: "Unloaded at Door 3 staging" },
    ],
  },
  {
    id: "DX-260918-037-P05",
    jobId: "DX-260918-037",
    palletNumber: 5,
    currentLocation: "ST-03",
    weightLbs: 2050,
    dimensions: { lengthIn: 48, widthIn: 40, heightIn: 66 },
    condition: "restacked",
    status: "staged",
    skuDescription: "Cream Soda (24x12oz Glass)",
    cartonCount: 84,
    photos: [SAMPLE_AFTER],
    movementHistory: [
      { id: "MOV-37-07", palletId: "DX-260918-037-P05", timestamp: "2026-09-18T08:30:00-06:00", fromLocation: "RW-01", toLocation: "ST-03", operator: "Marco S.", reason: "Rewrapped and moved to outbound staging" },
    ],
  },
  {
    id: "DX-260918-037-P06",
    jobId: "DX-260918-037",
    palletNumber: 6,
    currentLocation: "ST-03",
    weightLbs: 2080,
    dimensions: { lengthIn: 48, widthIn: 40, heightIn: 66 },
    condition: "restacked",
    status: "staged",
    skuDescription: "Cream Soda (24x12oz Glass)",
    cartonCount: 84,
    photos: [SAMPLE_AFTER],
    movementHistory: [
      { id: "MOV-37-08", palletId: "DX-260918-037-P06", timestamp: "2026-09-18T08:32:00-06:00", fromLocation: "RW-01", toLocation: "ST-03", operator: "Marco S.", reason: "Rewrapped and moved to outbound staging" },
    ],
  },
  {
    id: "DX-260918-037-P07",
    jobId: "DX-260918-037",
    palletNumber: 7,
    currentLocation: "ST-03",
    weightLbs: 2040,
    dimensions: { lengthIn: 48, widthIn: 40, heightIn: 66 },
    condition: "restacked",
    status: "staged",
    skuDescription: "Rocky Mountain Ginger Ale (24x12oz Cans)",
    cartonCount: 84,
    photos: [SAMPLE_AFTER],
    movementHistory: [
      { id: "MOV-37-09", palletId: "DX-260918-037-P07", timestamp: "2026-09-18T08:24:00-06:00", fromLocation: "Trailer RMB-5012", toLocation: "D-03", operator: "Marco S.", reason: "Unloaded at Door 3" },
      { id: "MOV-37-10", palletId: "DX-260918-037-P07", timestamp: "2026-09-18T08:34:00-06:00", fromLocation: "D-03", toLocation: "ST-03", operator: "Marco S.", reason: "Sound pallet staged for reload" },
    ],
  },
  {
    id: "DX-260918-037-P08",
    jobId: "DX-260918-037",
    palletNumber: 8,
    currentLocation: "RW-01",
    weightLbs: 1980,
    dimensions: { lengthIn: 48, widthIn: 40, heightIn: 64 },
    condition: "leaning",
    status: "in_rework",
    skuDescription: "Rocky Mountain Craft Root Beer (24x12oz Glass)",
    cartonCount: 72,
    photos: [SAMPLE_BEFORE_1, SAMPLE_BEFORE_2],
    movementHistory: [
      { id: "MOV-37-11", palletId: "DX-260918-037-P08", timestamp: "2026-09-18T08:26:00-06:00", fromLocation: "Trailer RMB-5012", toLocation: "D-03", operator: "Marco S.", reason: "Unloaded at Door 3" },
      { id: "MOV-37-12", palletId: "DX-260918-037-P08", timestamp: "2026-09-18T08:36:00-06:00", fromLocation: "D-03", toLocation: "RW-01", operator: "Marco S.", reason: "Shifted to Bay RW-01 turntable for restack triage" },
    ],
  },

  // --- Swift Job DX-260918-033 Pallets ---
  {
    id: "DX-260918-033-P01",
    jobId: "DX-260918-033",
    palletNumber: 1,
    currentLocation: "D-02",
    weightLbs: 1840,
    dimensions: { lengthIn: 48, widthIn: 40, heightIn: 64 },
    condition: "leaning",
    status: "in_rework",
    skuDescription: "Organic Pasta Sauce (12x24oz Glass)",
    cartonCount: 72,
    photos: [SAMPLE_BEFORE_1],
    movementHistory: [
      { id: "MOV-33-01", palletId: "DX-260918-033-P01", timestamp: "2026-09-18T08:10:00-06:00", fromLocation: "Trailer SWFT-55219", toLocation: "D-02", operator: "Luis R.", reason: "Offloaded for emergency rework" },
    ],
  },
  {
    id: "DX-260918-033-P02",
    jobId: "DX-260918-033",
    palletNumber: 2,
    currentLocation: "D-02",
    weightLbs: 1920,
    dimensions: { lengthIn: 48, widthIn: 40, heightIn: 66 },
    condition: "broken_runner",
    status: "in_rework",
    skuDescription: "Organic Pasta Sauce (12x24oz Glass)",
    cartonCount: 72,
    photos: [SAMPLE_BEFORE_2],
    movementHistory: [
      { id: "MOV-33-02", palletId: "DX-260918-033-P02", timestamp: "2026-09-18T08:14:00-06:00", fromLocation: "Trailer SWFT-55219", toLocation: "D-02", operator: "Luis R.", reason: "Damaged bottom runner" },
    ],
  },
  {
    id: "DX-260918-033-P03",
    jobId: "DX-260918-033",
    palletNumber: 3,
    currentLocation: "D-02",
    weightLbs: 1860,
    dimensions: { lengthIn: 48, widthIn: 40, heightIn: 62 },
    condition: "restacked",
    status: "staged",
    skuDescription: "Organic Pasta Sauce (12x24oz Glass)",
    cartonCount: 72,
    photos: [SAMPLE_AFTER],
    movementHistory: [
      { id: "MOV-33-03", palletId: "DX-260918-033-P03", timestamp: "2026-09-18T08:18:00-06:00", fromLocation: "Trailer SWFT-55219", toLocation: "D-02", operator: "Luis R.", reason: "Restacked and rewrapped" },
    ],
  },

  // --- Front Range Job DX-260918-041 Pallets (Storage) ---
  {
    id: "DX-260918-041-P01",
    jobId: "DX-260918-041",
    palletNumber: 1,
    currentLocation: "A-02",
    weightLbs: 1650,
    dimensions: { lengthIn: 48, widthIn: 40, heightIn: 58 },
    condition: "good",
    status: "stored",
    skuDescription: "Roasted Coffee Beans (50lb Sacks)",
    cartonCount: 32,
    photos: [SAMPLE_AFTER],
    movementHistory: [
      { id: "MOV-41-01", palletId: "DX-260918-041-P01", timestamp: "2026-09-16T14:00:00-06:00", fromLocation: "D-03", toLocation: "A-02", operator: "Luis R.", reason: "Stored in high-bay rack level 2" },
    ],
  },
  {
    id: "DX-260918-041-P02",
    jobId: "DX-260918-041",
    palletNumber: 2,
    currentLocation: "A-02",
    weightLbs: 1650,
    dimensions: { lengthIn: 48, widthIn: 40, heightIn: 58 },
    condition: "good",
    status: "stored",
    skuDescription: "Roasted Coffee Beans (50lb Sacks)",
    cartonCount: 32,
    photos: [SAMPLE_AFTER],
    movementHistory: [
      { id: "MOV-41-02", palletId: "DX-260918-041-P02", timestamp: "2026-09-16T14:05:00-06:00", fromLocation: "D-03", toLocation: "A-02", operator: "Luis R.", reason: "Stored in high-bay rack level 2" },
    ],
  },
  {
    id: "DX-260918-041-P03",
    jobId: "DX-260918-041",
    palletNumber: 3,
    currentLocation: "A-02",
    weightLbs: 1650,
    dimensions: { lengthIn: 48, widthIn: 40, heightIn: 58 },
    condition: "good",
    status: "stored",
    skuDescription: "Roasted Coffee Beans (50lb Sacks)",
    cartonCount: 32,
    photos: [SAMPLE_AFTER],
    movementHistory: [
      { id: "MOV-41-03", palletId: "DX-260918-041-P03", timestamp: "2026-09-16T14:10:00-06:00", fromLocation: "D-03", toLocation: "A-02", operator: "Luis R.", reason: "Stored in high-bay rack level 3" },
    ],
  },
];
export const INITIAL_JOBS: WarehouseJob[] = [
  // --- FLAGSHIP JOB: DX-260918-037 ---
  {
    id: "DX-260918-037",
    service: "Freight Rescue",
    customer: {
      id: "CUST-005",
      name: "Rocky Mountain Beverage Co",
      accountNumber: "DX-ACT-2088",
      contactName: "Tom Bradley",
      contactEmail: "tbradley@rmbev-demo.com",
      contactPhone: "(720) 555-8833",
    },
    carrier: { name: "Regional Hotshot Logistics", scac: "RHLX", contactPhone: "(720) 555-9000" },
    driver: { name: "Dan Kowalski", phone: "(720) 555-9000", cdlLast4: "5012" },
    trailer: "RMB-5012",
    bolNumber: "BOL-44910-RMB",
    poNumber: "PO-77381",
    status: "awaiting_approval",
    priority: "critical_emergency",
    arrival: "2026-09-18T08:00:00-06:00",
    appointment: "2026-09-18T08:15:00-06:00",
    dockDoor: "Door 3",
    warehouseLocations: ["D-03", "RW-01", "ST-03"],
    palletCount: 8,
    pallets: [
      "DX-260918-037-P01",
      "DX-260918-037-P02",
      "DX-260918-037-P03",
      "DX-260918-037-P04",
      "DX-260918-037-P05",
      "DX-260918-037-P06",
      "DX-260918-037-P07",
      "DX-260918-037-P08",
    ],
    labor: { hoursLogged: 1.5, assignedTech: "Marco S.", hourlyRate: 125.0 },
    equipment: ["FL-01 (Yale 5000lb)", "SR-01 (Orion Wrapper)"],
    materials: {
      palletsUsed: 2,
      palletType: "Grade-A Standard 48x40",
      wrapRollsUsed: 2,
      cornerBoardsUsed: 8,
    },
    quoteAmount: 450.0,
    pendingAdditions: 285.0,
    approvedAdditions: 0.0,
    authorizedAmount: 450.0,
    performedAmount: 450.0,
    billableAmount: 450.0,
    projectedAmount: 735.0,
    storageAmount: 0.0,
    billingStatus: "unbilled",
    billingReadinessStatus: "awaiting_authorization",
    notes: "Rejected at Commerce City grocery receiver due to load shift descending I-70 Floyd Hill. Transferred to Door 3. Pallet P08 identified with severe lean requiring restack authorization ($285 change order); sound pallets staged for reload.",
    photos: { before: [SAMPLE_BEFORE_1, SAMPLE_BEFORE_2], after: [SAMPLE_AFTER] },
    documents: {
      bolUrl: "#",
      rateConUrl: "#",
      signedCertUrl: "#",
      hasSignature: false,
    },
    timeline: [
      { id: "T1", stage: "Requested", timestamp: "09:42", label: "Driver Emergency Call", detail: "Driver reported cargo shift after receiver rejection; requested urgent bay", completed: true },
      { id: "T2", stage: "Arrived", timestamp: "10:18", label: "Gate Check-in", detail: "Trailer RMB-5012 checked in at 6030 Washington St; seal SL-501201 verified", completed: true },
      { id: "T3", stage: "Docked", timestamp: "10:27", label: "Assigned Door 3", detail: "Trailer backed into Door 3; dock leveler engaged and chocks set", completed: true },
      { id: "T4", stage: "Unloading", timestamp: "10:41", label: "Rework & Triage Started", detail: "Offloaded 8 pallets; Pallet P08 identified with severe tilt (>15°); restack required", completed: true },
      { id: "T5", stage: "Awaiting Approval", timestamp: "11:15", label: "Customer Approval Requested", detail: "Change order +$285.00 for Pallet P08 sent to Tom Bradley (Rocky Mountain Bev); awaiting authorization", completed: false, current: true },
      { id: "T6", stage: "Rework", timestamp: "Pending", label: "Rebuild & Rewrap", detail: "Restack damaged tiers onto Grade-A pallets; apply 80ga machine stretch wrap", completed: false },
      { id: "T7", stage: "Staging", timestamp: "Pending", label: "Outbound Reload Staging", detail: "Stage all 8 pallets at Door 3 / ST-03 for trailer reload", completed: false },
      { id: "T8", stage: "Billing Review", timestamp: "Pending", label: "Driver Signature & Closeout", detail: "Driver signs tablet certificate; invoice pushed to QuickBooks queue", completed: false },
    ],
    exceptions: ["EX-1049"],
    createdAt: "2026-09-18T09:42:00-06:00",
    updatedAt: "2026-09-18T11:15:00-06:00",
  },

  // --- JOB: DX-260918-031 (Waiting in Yard) ---
  {
    id: "DX-260918-031",
    service: "Shifted Pallets",
    customer: {
      id: "CUST-002",
      name: "Knight Dedicated Fleet",
      accountNumber: "DX-ACT-1022",
      contactName: "Dave Kowalski",
      contactEmail: "dkowalski@knight-demo.com",
      contactPhone: "(602) 555-4491",
    },
    carrier: { name: "Knight Transportation", scac: "KNIG", contactPhone: "(303) 555-9812" },
    driver: { name: "David Ross", phone: "(303) 555-9812", cdlLast4: "4910" },
    trailer: "KNIG-44102",
    bolNumber: "BOL-77312-KNIG",
    poNumber: "PO-99120",
    status: "waiting",
    priority: "critical_emergency",
    arrival: "2026-09-18T08:15:00-06:00",
    appointment: "2026-09-18T08:30:00-06:00",
    dockDoor: null,
    warehouseLocations: ["Spot Y-03"],
    palletCount: 22,
    pallets: [],
    labor: { hoursLogged: 0, assignedTech: "Unassigned", hourlyRate: 125.0 },
    equipment: ["FL-01 (Yale 5000lb)"],
    materials: { palletsUsed: 0, palletType: "Standard", wrapRollsUsed: 0, cornerBoardsUsed: 0 },
    quoteAmount: 520.0,
    approvedAdditions: 0,
    authorizedAmount: 520.0,
    performedAmount: 0.0,
    billableAmount: 0.0,
    billingStatus: "unbilled",
    billingReadinessStatus: "wip",
    notes: "Rejected at local grocery DC due to shift on I-70 mountain descent. Needs rapid restack for 14:00 redelivery.",
    photos: { before: [SAMPLE_BEFORE_1], after: [] },
    documents: { bolUrl: "#", rateConUrl: "#", hasSignature: false },
    timeline: [
      { id: "T1", stage: "Requested", timestamp: "2026-09-18T07:55:00-06:00", label: "Request Logged", detail: "Driver booked bay hold online", completed: true },
      { id: "T2", stage: "Arrived", timestamp: "2026-09-18T08:15:00-06:00", label: "Trailer In Yard", detail: "Checked in at Spot Y-03", completed: true, current: true },
      { id: "T3", stage: "Docked", timestamp: "Pending", label: "Dock Assignment", detail: "Waiting for open door", completed: false },
    ],
    exceptions: ["EX-1051"],
    createdAt: "2026-09-18T07:55:00-06:00",
    updatedAt: "2026-09-18T08:35:00-06:00",
  },

  // --- JOB: DX-260918-033 (In Progress / Active Rework) ---
  {
    id: "DX-260918-033",
    service: "Shifted Pallets",
    customer: {
      id: "CUST-001",
      name: "Swift Transportation Logistics",
      accountNumber: "DX-ACT-1008",
      contactName: "Sarah Jenkins",
      contactEmail: "sjenkins@swifttrans-demo.com",
      contactPhone: "(602) 555-0182",
    },
    carrier: { name: "Swift Transportation", scac: "SWFT", contactPhone: "(720) 555-0194" },
    driver: { name: "Marcus Vance", phone: "(720) 555-0194", cdlLast4: "2194" },
    trailer: "SWFT-55219",
    bolNumber: "BOL-90218-SWFT",
    status: "in_progress",
    priority: "expedited",
    arrival: "2026-09-18T07:45:00-06:00",
    appointment: "2026-09-18T08:00:00-06:00",
    dockDoor: "Door 2",
    warehouseLocations: ["D-02", "RW-01"],
    palletCount: 8,
    pallets: ["DX-260918-033-P01", "DX-260918-033-P02", "DX-260918-033-P03"],
    labor: { hoursLogged: 1.25, assignedTech: "Luis R.", hourlyRate: 125.0 },
    equipment: ["FL-02 (Hyster)", "SR-01 (Orion Turntable Wrapper)"],
    materials: { palletsUsed: 2, palletType: "Grade-A Standard", wrapRollsUsed: 1, cornerBoardsUsed: 4 },
    quoteAmount: 494.0,
    approvedAdditions: 0,
    authorizedAmount: 494.0,
    performedAmount: 320.0,
    billableAmount: 320.0,
    billingStatus: "unbilled",
    billingReadinessStatus: "wip",
    notes: "Active rework underway at Door 2. 3 pallets rebuilt, restacking remaining units.",
    photos: { before: [SAMPLE_BEFORE_1, SAMPLE_BEFORE_2], after: [SAMPLE_AFTER] },
    documents: { bolUrl: "#", signedCertUrl: "#", hasSignature: true },
    timeline: [
      { id: "T1", stage: "Requested", timestamp: "2026-09-18T07:15:00-06:00", label: "Intake", detail: "Phone intake completed", completed: true },
      { id: "T2", stage: "Arrived", timestamp: "2026-09-18T07:45:00-06:00", label: "Gate Arrival", detail: "Checked in on site", completed: true },
      { id: "T3", stage: "Docked", timestamp: "2026-09-18T07:55:00-06:00", label: "Door 2 Backed In", detail: "Backed into Door 2", completed: true },
      { id: "T4", stage: "In Progress", timestamp: "2026-09-18T08:10:00-06:00", label: "Rework Active", detail: "Pallet restack in progress", completed: true, current: true },
    ],
    exceptions: [],
    createdAt: "2026-09-18T07:15:00-06:00",
    updatedAt: "2026-09-18T08:40:00-06:00",
  },

  // --- JOB: DX-260918-035 (Dock Assigned) ---
  {
    id: "DX-260918-035",
    service: "Floor Transload",
    customer: {
      id: "CUST-003",
      name: "TQL Apex Freight Brokerage",
      accountNumber: "DX-ACT-1089",
      contactName: "Alex Rivera",
      contactEmail: "arivera@tql-demo.com",
      contactPhone: "(513) 555-7721",
    },
    carrier: { name: "Apex Line / TQL", scac: "TQLX", contactPhone: "(720) 555-4311" },
    driver: { name: "John Miller", phone: "(720) 555-4311", cdlLast4: "9018" },
    trailer: "TQLX-90184",
    bolNumber: "BOL-55102-TQL",
    status: "dock_assigned",
    priority: "standard",
    arrival: "2026-09-18T06:30:00-06:00",
    appointment: "2026-09-18T07:00:00-06:00",
    dockDoor: "Door 4",
    warehouseLocations: ["D-04"],
    palletCount: 26,
    pallets: [],
    labor: { hoursLogged: 2.0, assignedTech: "Marco S.", hourlyRate: 125.0 },
    equipment: ["FL-03 (Crown)", "EP-01 (Electric Pallet Jack)"],
    materials: { palletsUsed: 26, palletType: "Grade-A Standard", wrapRollsUsed: 4, cornerBoardsUsed: 0 },
    quoteAmount: 1001.0,
    approvedAdditions: 0,
    authorizedAmount: 1001.0,
    performedAmount: 450.0,
    billableAmount: 450.0,
    billingStatus: "unbilled",
    billingReadinessStatus: "wip",
    notes: "Import container floor-load transload to 26 pallets for regional LTL distribution.",
    photos: { before: [SAMPLE_BEFORE_1], after: [] },
    documents: { bolUrl: "#", hasSignature: false },
    timeline: [
      { id: "T1", stage: "Arrived", timestamp: "2026-09-18T06:30:00-06:00", label: "Gate In", detail: "Container trailer checked in", completed: true },
      { id: "T2", stage: "Docked", timestamp: "2026-09-18T07:00:00-06:00", label: "Door 4", detail: "Unloading underway", completed: true, current: true },
    ],
    exceptions: ["EX-1050"],
    createdAt: "2026-09-18T06:30:00-06:00",
    updatedAt: "2026-09-18T08:20:00-06:00",
  },

  // --- JOB: DX-260918-039 (Staged Outbound) ---
  {
    id: "DX-260918-039",
    service: "Cross-Dock",
    customer: {
      id: "CUST-001",
      name: "Swift Transportation Logistics",
      accountNumber: "DX-ACT-1008",
      contactName: "Sarah Jenkins",
      contactEmail: "sjenkins@swifttrans-demo.com",
      contactPhone: "(602) 555-0182",
    },
    carrier: { name: "J.B. Hunt Transport", scac: "JBHT", contactPhone: "(303) 555-2144" },
    driver: { name: "Robert Hayes", phone: "(303) 555-2144" },
    trailer: "JBHT-33910",
    bolNumber: "BOL-66129-JBHT",
    status: "staged",
    priority: "standard",
    arrival: "2026-09-18T08:40:00-06:00",
    dockDoor: "Door 5",
    warehouseLocations: ["D-05", "ST-03"],
    palletCount: 22,
    pallets: [],
    labor: { hoursLogged: 1.5, assignedTech: "Luis R.", hourlyRate: 125.0 },
    equipment: ["FL-02 (Hyster)"],
    materials: { palletsUsed: 0, palletType: "None", wrapRollsUsed: 0, cornerBoardsUsed: 0 },
    quoteAmount: 330.0,
    approvedAdditions: 0,
    authorizedAmount: 330.0,
    performedAmount: 330.0,
    billableAmount: 330.0,
    billingStatus: "unbilled",
    billingReadinessStatus: "needs_documentation",
    notes: "Cross-dock transfer from inbound Swift trailer to outbound J.B. Hunt trailer. Staged at Door 5.",
    photos: { before: [SAMPLE_BEFORE_1], after: [SAMPLE_AFTER] },
    documents: { bolUrl: "#", rateConUrl: "#", hasSignature: true },
    timeline: [
      { id: "T1", stage: "Arrived", timestamp: "2026-09-18T08:40:00-06:00", label: "Trailer In", detail: "Arrived at Door 5", completed: true },
      { id: "T2", stage: "Staged", timestamp: "2026-09-18T09:00:00-06:00", label: "Pallets Staged", detail: "Staged at Door 5 ready to load", completed: true, current: true },
    ],
    exceptions: [],
    createdAt: "2026-09-18T08:40:00-06:00",
    updatedAt: "2026-09-18T09:00:00-06:00",
  },

  // --- JOB: DX-260918-041 (High-Bay Storage) ---
  {
    id: "DX-260918-041",
    service: "Short-Term Storage",
    customer: {
      id: "CUST-004",
      name: "Front Range Regional Foods",
      accountNumber: "DX-ACT-2041",
      contactName: "Elena Rostova",
      contactEmail: "erostova@frontrangefoods-demo.com",
      contactPhone: "(303) 555-6612",
    },
    carrier: { name: "Front Range Dedicated", contactPhone: "(303) 555-6612" },
    driver: { name: "Viktor Petrov", phone: "(303) 555-6612" },
    trailer: "FRF-4419",
    bolNumber: "BOL-10928-FRF",
    status: "staged",
    priority: "standard",
    arrival: "2026-09-16T13:40:00-06:00",
    dockDoor: null,
    warehouseLocations: ["A-02"],
    palletCount: 16,
    pallets: ["DX-260918-041-P01", "DX-260918-041-P02", "DX-260918-041-P03"],
    labor: { hoursLogged: 1.0, assignedTech: "Luis R.", hourlyRate: 125.0 },
    equipment: ["FL-01 (Yale High Reach)"],
    materials: { palletsUsed: 0, palletType: "None", wrapRollsUsed: 0, cornerBoardsUsed: 0 },
    quoteAmount: 640.0,
    approvedAdditions: 0,
    storageAmount: 56.0,
    authorizedAmount: 696.0,
    performedAmount: 696.0,
    billableAmount: 696.0,
    billingStatus: "pending_review",
    billingReadinessStatus: "needs_review",
    notes: "16 pallets organic coffee beans staged in Rack A-02. Retention agreed through Sep 25 pending retailer warehouse slotting.",
    photos: { before: [], after: [SAMPLE_AFTER] },
    documents: { bolUrl: "#", hasSignature: true },
    timeline: [
      { id: "T1", stage: "Arrived", timestamp: "2026-09-16T13:40:00-06:00", label: "Inbound Check-in", detail: "Pallets received", completed: true },
      { id: "T2", stage: "Stored", timestamp: "2026-09-16T14:15:00-06:00", label: "Racked A-02", detail: "High-bay slotting complete", completed: true, current: true },
    ],
    exceptions: [],
    createdAt: "2026-09-16T13:40:00-06:00",
    updatedAt: "2026-09-18T08:00:00-06:00",
  },

  // --- JOB: DX-260918-043 (Ready for Billing) ---
  {
    id: "DX-260918-043",
    service: "Axle Rebalance",
    customer: {
      id: "CUST-002",
      name: "Knight Dedicated Fleet",
      accountNumber: "DX-ACT-1022",
      contactName: "Dave Kowalski",
      contactEmail: "dkowalski@knight-demo.com",
      contactPhone: "(602) 555-4491",
    },
    carrier: { name: "Werner Enterprises", scac: "WRNR", contactPhone: "(720) 555-7791" },
    driver: { name: "Carlos Mendez", phone: "(720) 555-7791" },
    trailer: "WRNR-88214",
    bolNumber: "BOL-88214-WRNR",
    status: "ready_for_billing",
    priority: "expedited",
    arrival: "2026-09-18T05:50:00-06:00",
    dockDoor: null,
    warehouseLocations: ["Spot Y-08"],
    palletCount: 4,
    pallets: [],
    labor: { hoursLogged: 1.5, assignedTech: "Marco S.", hourlyRate: 125.0 },
    equipment: ["FL-01 (Yale)", "Axle Scale Verifier"],
    materials: { palletsUsed: 0, palletType: "None", wrapRollsUsed: 1, cornerBoardsUsed: 0 },
    quoteAmount: 385.0,
    approvedAdditions: 0,
    authorizedAmount: 385.0,
    performedAmount: 385.0,
    billableAmount: 385.0,
    billingStatus: "pending_review",
    billingReadinessStatus: "ready_to_invoice",
    notes: "Overweight citation risk at Fort Collins port of entry (drive axle +1,800 lbs). Shifted 4 pallets from nose to tail.",
    photos: { before: [SAMPLE_BEFORE_1], after: [SAMPLE_AFTER] },
    documents: { bolUrl: "#", signedCertUrl: "#", hasSignature: true },
    timeline: [
      { id: "T1", stage: "Arrived", timestamp: "2026-09-18T05:50:00-06:00", label: "Check-in", detail: "Overweight axle assist", completed: true },
      { id: "T2", stage: "Rebalance", timestamp: "2026-09-18T07:15:00-06:00", label: "Pallets Shifted", detail: "4 pallets moved to tandem position", completed: true },
      { id: "T3", stage: "Ready for Billing", timestamp: "2026-09-18T08:00:00-06:00", label: "Driver Signed", detail: "Ready for QuickBooks export", completed: true, current: true },
    ],
    exceptions: [],
    createdAt: "2026-09-18T05:50:00-06:00",
    updatedAt: "2026-09-18T08:05:00-06:00",
    completedAt: "2026-09-18T08:00:00-06:00",
  },

  // --- JOB: DX-260918-045 (Completed & Invoiced) ---
  {
    id: "DX-260918-045",
    service: "Pallet Swap",
    customer: {
      id: "CUST-001",
      name: "Swift Transportation Logistics",
      accountNumber: "DX-ACT-1008",
      contactName: "Sarah Jenkins",
      contactEmail: "sjenkins@swifttrans-demo.com",
      contactPhone: "(602) 555-0182",
    },
    carrier: { name: "Schneider National", scac: "SNLU", contactPhone: "(303) 555-4411" },
    driver: { name: "Kevin O'Connor", phone: "(303) 555-4411" },
    trailer: "SNLU-11048",
    bolNumber: "BOL-11048-SNLU",
    status: "completed",
    priority: "standard",
    arrival: "2026-09-18T04:20:00-06:00",
    dockDoor: null,
    warehouseLocations: ["Spot Y-12"],
    palletCount: 12,
    pallets: [],
    labor: { hoursLogged: 2.0, assignedTech: "Luis R.", hourlyRate: 125.0 },
    equipment: ["FL-02 (Hyster)"],
    materials: { palletsUsed: 12, palletType: "Grade-A Standard 48x40", wrapRollsUsed: 2, cornerBoardsUsed: 0 },
    quoteAmount: 622.0,
    approvedAdditions: 0,
    authorizedAmount: 622.0,
    performedAmount: 622.0,
    billableAmount: 622.0,
    billingStatus: "invoiced",
    billingReadinessStatus: "invoiced",
    notes: "Broken boards on 12 pallets swapped to grade-A wooden pallets. Sign-off received and invoiced via QuickBooks.",
    photos: { before: [SAMPLE_BEFORE_2], after: [SAMPLE_AFTER] },
    documents: { bolUrl: "#", signedCertUrl: "#", hasSignature: true },
    timeline: [
      { id: "T1", stage: "Arrived", timestamp: "2026-09-18T04:20:00-06:00", label: "Early Intake", detail: "Broken runner inspection", completed: true },
      { id: "T2", stage: "Swap Done", timestamp: "2026-09-18T06:30:00-06:00", label: "Pallets Exchanged", detail: "Transferred onto fresh wood", completed: true },
      { id: "T3", stage: "Completed", timestamp: "2026-09-18T07:10:00-06:00", label: "Invoiced", detail: "Driver departed; invoice sent", completed: true, current: true },
    ],
    exceptions: [],
    createdAt: "2026-09-18T04:20:00-06:00",
    updatedAt: "2026-09-18T07:15:00-06:00",
    completedAt: "2026-09-18T07:10:00-06:00",
  },
];

export const INITIAL_CAPITAL_ASSETS: CapitalAsset[] = [
  {
    id: "FL-01",
    name: "Yale ERP050 5,000 lb Cushion Electric Forklift",
    category: "electric_forklift",
    status: "in_use",
    currentArea: "RW-01",
    currentJobId: "DX-260918-037",
    assignedOperator: "Marco S.",
    batteryPercent: 84,
    meterHours: 3221,
    nextServiceHours: 3250,
    lastInspectionDate: "2026-09-05",
    inspectionStatus: "due_soon",
    notes: "Primary flagship rework unit. 29 hours until 250-hour preventative maintenance interval.",
  },
  {
    id: "FL-02",
    name: "Hyster J40XNT 4,000 lb 3-Wheel Electric Forklift",
    category: "electric_forklift",
    status: "in_use",
    currentArea: "D-02",
    currentJobId: "DX-260918-033",
    assignedOperator: "Luis R.",
    batteryPercent: 91,
    meterHours: 2410,
    nextServiceHours: 2600,
    lastInspectionDate: "2026-09-10",
    inspectionStatus: "compliant",
    notes: "Assigned to Door 2 shifted pallets rework; high maneuverability inside dry vans.",
  },
  {
    id: "FL-03",
    name: "Crown RC 5500 Stand-Up Counterbalanced Forklift",
    category: "standup_forklift",
    status: "charging",
    currentArea: "Charging Bay 1",
    currentJobId: undefined,
    assignedOperator: undefined,
    batteryPercent: 62,
    meterHours: 4180,
    nextServiceHours: 4200,
    lastInspectionDate: "2026-08-28",
    inspectionStatus: "due_soon",
    notes: "On rapid charge cycle; staged for 13:00 cross-dock transfer surge.",
  },
  {
    id: "EP-01",
    name: "Raymond 8410 End-Rider Electric Pallet Jack",
    category: "pallet_jack",
    status: "available",
    currentArea: "ST-01",
    currentJobId: undefined,
    assignedOperator: undefined,
    batteryPercent: 95,
    meterHours: 1140,
    nextServiceHours: 1500,
    lastInspectionDate: "2026-09-12",
    inspectionStatus: "compliant",
    notes: "Available for floor transit and staging lane moves.",
  },
  {
    id: "SR-01",
    name: "Orion Rotary Turntable Semi-Automatic Stretch Wrapper",
    category: "stretch_wrapper",
    status: "in_use",
    currentArea: "RW-01",
    currentJobId: "DX-260918-037",
    assignedOperator: "Marco S.",
    batteryPercent: undefined,
    meterHours: 1845,
    nextServiceHours: 2000,
    lastInspectionDate: "2026-09-08",
    inspectionStatus: "compliant",
    notes: "Operating in Bay RW-01 for 80-gauge prestretch stabilization (<1° lean compliance).",
  },
  {
    id: "SC-01",
    name: "Intercomp Portable Axle Scale & Weight Pad System",
    category: "axle_scale",
    status: "available",
    currentArea: "Spot Y-08",
    currentJobId: "DX-260918-043",
    assignedOperator: "Marco S.",
    batteryPercent: 88,
    meterHours: 620,
    nextServiceHours: 1000,
    lastInspectionDate: "2026-09-01",
    inspectionStatus: "compliant",
    notes: "NIST certified calibration for DOT legal bridge weight verification.",
  },
];

export const INITIAL_PERSONNEL: WarehousePersonnel[] = [
  {
    id: "TECH-01",
    name: "Marco S.",
    role: "Lead Dock Tech & Rework Specialist",
    status: "active",
    currentJobId: "DX-260918-037",
    currentArea: "RW-01",
    hoursLoggedToday: 5.0,
    assignedAssetId: "FL-01",
    certifications: ["OSHA Class I & IV Forklift", "Food-Grade Sanitation", "HAZMAT Awareness"],
  },
  {
    id: "TECH-02",
    name: "Luis R.",
    role: "Warehouse Forklift Technician",
    status: "active",
    currentJobId: "DX-260918-033",
    currentArea: "D-02",
    hoursLoggedToday: 4.75,
    assignedAssetId: "FL-02",
    certifications: ["OSHA Class I & II Forklift", "Electric Pallet Jack Specialist"],
  },
  {
    id: "TECH-03",
    name: "Dave M.",
    role: "Freight Rework & Staging Associate",
    status: "available",
    currentJobId: undefined,
    currentArea: "ST-03",
    hoursLoggedToday: 3.5,
    assignedAssetId: "EP-01",
    certifications: ["OSHA Pallet Jack", "Cargo Securement & Banding"],
  },
  {
    id: "DISP-01",
    name: "Sarah Lin",
    role: "Operations & Dispatch Manager",
    status: "active",
    currentJobId: undefined,
    currentArea: "Dispatch Desk",
    hoursLoggedToday: 6.0,
    certifications: ["Terminal Operations Certification", "FMCSA Compliance Auditor"],
  },
];

